apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fl-data-pvc-cblee
  namespace: cblee-credo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Adjust size based on your data needs 